version: '3.8'

services:

  web:
    build:
       context: ./app
       dockerfile: Dockerfile
    container_name: web
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network


  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - 9200:9200
    env_file:
      - .env
    networks:
      - app-network

  etl:
    build:
      context: ./pg_to_es
      dockerfile: Dockerfile
    container_name: etl_postgres_to_elastic
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
    command: python main.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_volume:
  elastic_volume:
  static_volume:
  media_volume:
