version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - 9200:9200
    env_file:
      - .env

  db:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres_volume:
  elastic_volume: